# Calculate the amplitudes

This notebook is used to calculate the amplitudes of the seismograms.

Agentic AI was used in this notebook.

By Hiroto Bito

In [7]:
# Import necessary libraries
import os
import sys
import pandas as pd
import numpy as np
import time
from tqdm import tqdm

from obspy import read, UTCDateTime
from obspy.clients.fdsn import Client
from obspy.core.stream import Stream

parent_dir = '/home/hbito/cascadia_obs_ensemble/utils'
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from data_client import get_waveforms

In [8]:
# Read the data frame
datasets_dir =  '/wd1/hbito_data/data/datasets_all_regions'
path_assigned_picks_df = f'{datasets_dir}/Cascadia_updated_catalog_picks_assignment_ver_3.csv'

# Prepare output CSV path 
output_csv_path = f'{datasets_dir}/Cascadia_updated_catalog_picks_assignment_ver_3_w_amp_test.csv'

# File to save skipped picks
skipped_csv_path = f'{datasets_dir}/calculate_amplitudes_skipped_picks_test.csv'

assigned_picks_df = pd.read_csv(path_assigned_picks_df, index_col=False).copy()
assigned_picks_df.head()

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3

In [9]:
# Define the arguments
window_before = 30 # in sec
window_after = 150 # in sec

window_before_calc_amplitude = 0.5 # in sec
window_after_calc_amplitude = 2 # in sec

source = 'pnwstore'

freq_highpass = 2 # in Hz
new_sampling_rate = 100 # in Hz

In [10]:
df = assigned_picks_df.iloc[:100]

In [11]:
# Run the loop
amplitudes = []

for idx, row in tqdm(df.iterrows(), total=len(df)):

    # Define the arguments 
    arid = row['arid']
    orid = row['idx']
    date, _time = row['time'].split(' ')
    datetime_str = date+'T'+_time
    origin_time = UTCDateTime(datetime_str)  # Accept ISO string directly

    time_pick_str = row['time_pick'] 
    time_pick = UTCDateTime(time_pick_str)  # Accept ISO string directly

    network = row['station'].split('.')[0].strip()
    station = row['station'].split('.')[1].strip()
    channel = '*H*'

    starttime = time_pick - window_before 
    endtime = time_pick + window_after

    starttime_trim = time_pick - window_before_calc_amplitude 
    endtime_trim = time_pick + window_after_calc_amplitude

    # Print the number of items in amplitudes for validation
    print('len(amplitudes)',len(amplitudes))    

    # Request a waveform
    time.sleep(0.1)

    try:
        st = get_waveforms(network=network, station=station, channel=channel,
                            starttime=starttime, endtime=endtime,
                            source=source)
    except Exception as e:
        print(f"Request failed: {e}")

        # Save amplitude to the output DataFrame and CSV on the fly
        amp = np.nan
        amplitudes.append(amp)

        # Save skipped info to CSV
        skipped_info = {
            'arid': arid,
            'orid': orid,
            'network': network,
            'station': station,
            'channel': channel,
            'origin_time': origin_time,
            'time_pick': time_pick,
            'starttime': starttime,
            'endtime': endtime,
            'reason': f'Request failed: {e}'
        }
        df_skipped = pd.DataFrame([skipped_info])
        if not os.path.isfile(skipped_csv_path):
            df_skipped.to_csv(skipped_csv_path, mode='w', header=True, index=False)
        else:
            df_skipped.to_csv(skipped_csv_path, mode='a', header=False, index=False)

        continue
        

    # time.sleep(0.1)


    # Create a new stream
    sdata = Stream()
    
    # Check if loaded data have a vertical component (minimum requirement)
    has_Z = bool(st.select(channel='??Z'))
    # Check for the presence of HH, BH, and EH channels
    has_HH = bool(st.select(channel='HH?'))
    has_BH = bool(st.select(channel='BH?'))
    has_EH = bool(st.select(channel='EH?'))

    if not has_Z:
        e = f'No Vertical Component Data Present at {network}.{station} with HHZ, BHZ or EHZ channels at {time_pick_str}. Skipping'
        print(e)

        # Save amplitude in the list
        amp = np.nan
        amplitudes.append(amp)

        # Save skipped info to CSV
        skipped_info = {
            'arid': arid,
            'orid': orid,
            'network': network,
            'station': station,
            'channel': channel,
            'origin_time': origin_time,
            'time_pick': time_pick,
            'starttime': starttime,
            'endtime': endtime,
            'reason': f'Request failed: {e}'
        }
        df_skipped = pd.DataFrame([skipped_info])
        if not os.path.isfile(skipped_csv_path):
            df_skipped.to_csv(skipped_csv_path, mode='w', header=True, index=False)
        else:
            df_skipped.to_csv(skipped_csv_path, mode='a', header=False, index=False)

        continue

    # Apply selection logic based on channel presence
    if has_HH:
        # If all HH, BH, and EH, channels are present, select only HH
        sdata += st.select(channel='HH*')
    elif has_BH:
        # If BH and EH channels are present, select only BH
        sdata += st.select(channel='BH*')
    elif has_EH:
        # If only EH channels are present, select only EH
        # NTS: This may result in getting only vertical component data - EH? is used for PNSN analog stations
        # NTS: This may also be tricky for pulling full day-volumes because the sampling rate shifts for
        #      analog stations due to the remote digitization scheme used with analog stations
        sdata += st.select(channel='EH*')
    else:
        e = f'No data available at {network}.{station} with HHZ, BHZ or EHZ channels at {time_pick_str}. Skipping.'
        print(e)

        # Save amplitude to the output DataFrame and CSV on the fly
        amp = np.nan
        amplitudes.append(amp)

        # Save skipped info to CSV
        skipped_info = {
            'arid': arid,
            'orid': orid,
            'network': network,
            'station': station,
            'channel': channel,
            'origin_time': origin_time,
            'time_pick': time_pick,
            'starttime': starttime,
            'endtime': endtime,
            'reason': f'Request failed: {e}'
        }
        df_skipped = pd.DataFrame([skipped_info])
        if not os.path.isfile(skipped_csv_path):
            df_skipped.to_csv(skipped_csv_path, mode='w', header=True, index=False)
        else:
            df_skipped.to_csv(skipped_csv_path, mode='a', header=False, index=False)
        continue

    # Resample
    sdata.resample(new_sampling_rate)
        
    # Apply highpass filter
    sdata.detrend(type='demean')
    sdata.taper(max_percentage=0.05)
    sdata.filter(type='highpass', freq=freq_highpass)

    trimmed_data = sdata.copy().trim(starttime=starttime_trim, endtime=endtime_trim)

    max_amp = 0
    for tr in trimmed_data:
        max_amp = max(max_amp, abs(tr.data).max())

    amplitudes.append(max_amp)

# Append to DataFrame
df.loc[:,"Amplitude"] = amplitudes

df.to_csv(output_csv_path, index=False)

  0%|          | 0/100 [00:00<?, ?it/s]

len(amplitudes) 0

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  1%|          | 1/100 [00:02<03:19,  2.02s/it]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 1

  2%|▏         | 2/100 [00:02<01:41,  1.03s/it]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  3%|▎         | 3/100 [00:02<01:01,  1.57it/s]

len(amplitudes) 2
len(amplitudes) 3

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  4%|▍         | 4/100 [00:03<01:06,  1.45it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 4

  5%|▌         | 5/100 [00:03<00:55,  1.71it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 5

  6%|▌         | 6/100 [00:04<00:52,  1.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 6

  7%|▋         | 7/100 [00:04<00:42,  2.19it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 7

  8%|▊         | 8/100 [00:04<00:39,  2.35it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 8

  9%|▉         | 9/100 [00:05<00:32,  2.77it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 9

 10%|█         | 10/100 [00:05<00:29,  3.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 10

 11%|█         | 11/100 [00:05<00:26,  3.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 11

 12%|█▏        | 12/100 [00:05<00:25,  3.51it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 12

 13%|█▎        | 13/100 [00:06<00:27,  3.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 13

 14%|█▍        | 14/100 [00:06<00:31,  2.71it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 14

 15%|█▌        | 15/100 [00:07<00:34,  2.46it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 15

 16%|█▌        | 16/100 [00:07<00:29,  2.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 16

 17%|█▋        | 17/100 [00:07<00:33,  2.48it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 17

 18%|█▊        | 18/100 [00:08<00:35,  2.33it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 18

 19%|█▉        | 19/100 [00:08<00:30,  2.65it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 19

 20%|██        | 20/100 [00:09<00:32,  2.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 20

 21%|██        | 21/100 [00:09<00:28,  2.78it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 21

 22%|██▏       | 22/100 [00:09<00:30,  2.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 22

 23%|██▎       | 23/100 [00:10<00:32,  2.38it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 23

 24%|██▍       | 24/100 [00:10<00:27,  2.75it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 24

 25%|██▌       | 25/100 [00:10<00:24,  3.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 25

 26%|██▌       | 26/100 [00:11<00:22,  3.35it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 26

 27%|██▋       | 27/100 [00:11<00:25,  2.86it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 27

 28%|██▊       | 28/100 [00:11<00:28,  2.56it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 28

 29%|██▉       | 29/100 [00:12<00:25,  2.83it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 29

 30%|███       | 30/100 [00:12<00:27,  2.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 30

 31%|███       | 31/100 [00:13<00:26,  2.59it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 31

 32%|███▏      | 32/100 [00:13<00:28,  2.37it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 33%|███▎      | 33/100 [00:13<00:23,  2.91it/s]

len(amplitudes) 32
len(amplitudes) 33

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 34%|███▍      | 34/100 [00:13<00:18,  3.52it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 34

 35%|███▌      | 35/100 [00:14<00:17,  3.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 35

 36%|███▌      | 36/100 [00:14<00:15,  4.01it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 37%|███▋      | 37/100 [00:14<00:14,  4.35it/s]

len(amplitudes) 36
len(amplitudes) 37

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 38%|███▊      | 38/100 [00:14<00:13,  4.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 39%|███▉      | 39/100 [00:14<00:12,  4.98it/s]

len(amplitudes) 38
len(amplitudes) 39

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 40%|████      | 40/100 [00:15<00:12,  4.89it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 40

 41%|████      | 41/100 [00:15<00:12,  4.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 41

 42%|████▏     | 42/100 [00:15<00:12,  4.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 42

 43%|████▎     | 43/100 [00:15<00:12,  4.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 44%|████▍     | 44/100 [00:15<00:10,  5.24it/s]

len(amplitudes) 43
len(amplitudes) 44

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 45%|████▌     | 45/100 [00:16<00:10,  5.06it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 46%|████▌     | 46/100 [00:16<00:09,  5.61it/s]

len(amplitudes) 45
len(amplitudes) 46

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 47%|████▋     | 47/100 [00:16<00:11,  4.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 47

 48%|████▊     | 48/100 [00:16<00:13,  3.86it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 48

 49%|████▉     | 49/100 [00:17<00:13,  3.84it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 49

 50%|█████     | 50/100 [00:17<00:12,  4.07it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 51%|█████     | 51/100 [00:17<00:10,  4.74it/s]

len(amplitudes) 50
len(amplitudes) 51

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 52%|█████▏    | 52/100 [00:17<00:10,  4.38it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 52

 53%|█████▎    | 53/100 [00:18<00:11,  4.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 54%|█████▍    | 54/100 [00:18<00:09,  4.68it/s]

len(amplitudes) 53
len(amplitudes) 54

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 55%|█████▌    | 55/100 [00:18<00:09,  4.72it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 55

 56%|█████▌    | 56/100 [00:18<00:09,  4.73it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 57%|█████▋    | 57/100 [00:18<00:08,  5.23it/s]

len(amplitudes) 56
len(amplitudes) 57

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 58%|█████▊    | 58/100 [00:18<00:07,  5.67it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 58

 59%|█████▉    | 59/100 [00:19<00:08,  5.07it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 59

 60%|██████    | 60/100 [00:19<00:08,  4.92it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 60

 61%|██████    | 61/100 [00:19<00:07,  4.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 61

 62%|██████▏   | 62/100 [00:19<00:07,  4.79it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 62

 63%|██████▎   | 63/100 [00:20<00:07,  4.76it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 63

 64%|██████▍   | 64/100 [00:20<00:07,  4.74it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 65%|██████▌   | 65/100 [00:20<00:06,  5.25it/s]

len(amplitudes) 64
len(amplitudes) 65

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 66%|██████▌   | 66/100 [00:20<00:06,  5.09it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 66

 67%|██████▋   | 67/100 [00:20<00:06,  4.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 67

 68%|██████▊   | 68/100 [00:21<00:06,  4.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 69%|██████▉   | 69/100 [00:21<00:05,  5.41it/s]

len(amplitudes) 68
len(amplitudes) 69

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 70%|███████   | 70/100 [00:21<00:05,  5.13it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 71%|███████   | 71/100 [00:21<00:05,  5.68it/s]

len(amplitudes) 70
len(amplitudes) 71

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 72%|███████▏  | 72/100 [00:21<00:04,  6.11it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 72

 73%|███████▎  | 73/100 [00:21<00:04,  5.61it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 73

 74%|███████▍  | 74/100 [00:22<00:04,  5.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 75%|███████▌  | 75/100 [00:22<00:04,  5.38it/s]

len(amplitudes) 74
len(amplitudes) 75

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 76%|███████▌  | 76/100 [00:22<00:04,  5.75it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 76

 77%|███████▋  | 77/100 [00:22<00:04,  5.40it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 77

 78%|███████▊  | 78/100 [00:22<00:04,  5.15it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 78

 79%|███████▉  | 79/100 [00:23<00:05,  3.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 80%|████████  | 80/100 [00:23<00:04,  4.57it/s]

len(amplitudes) 79
len(amplitudes) 80

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 81%|████████  | 81/100 [00:23<00:04,  4.60it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 81

 82%|████████▏ | 82/100 [00:23<00:03,  4.57it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 83%|████████▎ | 83/100 [00:23<00:03,  5.19it/s]

len(amplitudes) 82
len(amplitudes) 83

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 84%|████████▍ | 84/100 [00:24<00:02,  5.59it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 85%|████████▌ | 85/100 [00:24<00:02,  5.98it/s]

len(amplitudes) 84
len(amplitudes) 85

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 86%|████████▌ | 86/100 [00:24<00:02,  6.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 86

 87%|████████▋ | 87/100 [00:24<00:02,  5.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 87

 88%|████████▊ | 88/100 [00:24<00:02,  5.33it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 88

 89%|████████▉ | 89/100 [00:24<00:02,  5.14it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 89

 90%|█████████ | 90/100 [00:25<00:02,  4.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 91%|█████████ | 91/100 [00:25<00:01,  5.21it/s]

len(amplitudes) 90
len(amplitudes) 91

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 92%|█████████▏| 92/100 [00:25<00:01,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 92

 93%|█████████▎| 93/100 [00:25<00:01,  4.94it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 93

 94%|█████████▍| 94/100 [00:26<00:01,  4.86it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 94

 95%|█████████▌| 95/100 [00:26<00:01,  4.79it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 95

 96%|█████████▌| 96/100 [00:26<00:00,  4.78it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 96

 97%|█████████▋| 97/100 [00:26<00:00,  4.71it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 98%|█████████▊| 98/100 [00:26<00:00,  5.27it/s]

len(amplitudes) 97
len(amplitudes) 98

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 99%|█████████▉| 99/100 [00:26<00:00,  5.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
100%|██████████| 100/100 [00:27<00:00,  3.69it/s]

len(amplitudes) 99

/tmp/ipykernel_3654391/3953987420.py:165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,"Amplitude"] = amplitudes

In [14]:
assigned_picks_df_w_amp = pd.read_csv(output_csv_path, index_col=False)
assigned_picks_df_w_amp

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation,Amplitude
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.147,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,528.446789
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.147,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0,73.754697
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.147,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,897.628533
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.147,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0,1671.719173
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.147,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3,60.723817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,2010-01-01T08:52:03.838400Z,PB.B005,P,0.023,3,95,47.97665,-122.90617,20.910,0.756,2010-01-01 08:51:56.196000+00:00,0.465,10,10,20,48.059547,-123.503281,302.7,60.551756
96,96,2010-01-01T08:52:09.048400Z,PB.B011,P,-1.025,3,96,47.97665,-122.90617,20.910,0.756,2010-01-01 08:51:56.196000+00:00,0.465,10,10,20,48.649544,-123.448189,22.0,73.087010
97,97,2010-01-01T08:52:14.310000Z,CN.GOBB,P,0.069,3,97,47.97665,-122.90617,20.910,0.756,2010-01-01 08:51:56.196000+00:00,0.465,10,10,20,48.949300,-123.510500,173.0,55.218456
98,98,2010-01-01T08:52:15.378400Z,PB.B926,P,-0.397,3,98,47.97665,-122.90617,20.910,0.756,2010-01-01 08:51:56.196000+00:00,0.465,10,10,20,48.820202,-124.131203,191.6,18.716581
99,99,2010-01-01T08:52:20.700000Z,CN.BIB,P,0.497,3,99,47.97665,-122.90617,20.910,0.756,2010-01-01 08:51:56.196000+00:00,0.465,10,10,20,49.410300,-123.310500,38.0,20.089275

In [15]:
skipped_picks_df = pd.read_csv(skipped_csv_path, index_col=False)
skipped_picks_df

FileNotFoundError: [Errno 2] No such file or directory: '/wd1/hbito_data/data/datasets_all_regions/calculate_amplitudes_skipped_picks_test.csv'