# Calculate the amplitudes

This notebook is used to calculate the amplitudes of the seismograms.

Agentic AI was used in this notebook.

By Hiroto Bito

In [22]:
# Import necessary libraries
import os
import sys
import pandas as pd
import numpy as np
import time
from tqdm import tqdm

from obspy import read, UTCDateTime
from obspy.clients.fdsn import Client
from obspy.core.stream import Stream

parent_dir = '/home/hbito/cascadia_obs_ensemble/utils'
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from data_client import get_waveforms

In [23]:
# Read the data frame
datasets_dir =  '/wd1/hbito_data/data/datasets_all_regions'
path_assigned_picks_df = f'{datasets_dir}/Cascadia_updated_catalog_picks_assignment_ver_3.csv'

# Prepare output CSV path 
output_csv_path = f'{datasets_dir}/Cascadia_updated_catalog_picks_assignment_ver_3_w_amp_test.csv'

# File to save skipped picks
skipped_csv_path = f'{datasets_dir}/calculate_amplitudes_skipped_picks_test.csv'

assigned_picks_original_df = pd.read_csv(path_assigned_picks_df, index_col=False).copy()

test

In [15]:
assigned_picks_original_df

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004330,1004330,2015-06-23T23:18:40.885798Z,7D.J11D,S,0.044,63886,1004330,43.33308,-127.31240,6.0615,0.694,2015-06-23 23:18:19.457000+00:00,0.447,4,5,9,43.541599,-126.368599,-3000.8
1004331,1004331,2015-06-23T23:18:48.573898Z,7D.G35D,S,0.358,63886,1004331,43.33308,-127.31240,6.0615,0.694,2015-06-23 23:18:19.457000+00:00,0.447,4,5,9,42.555698,-126.399002,-2822.6
1004332,1004332,2015-06-23T23:18:50.458298Z,7D.J19D,S,0.300,63886,1004332,43.33308,-127.31240,6.0615,0.694,2015-06-23 23:18:19.457000+00:00,0.447,4,5,9,44.179001,-126.271202,-2955.4
1004333,1004333,2015-06-23T23:18:56.689277Z,7D.J10D,S,0.432,63886,1004333,43.33308,-127.31240,6.0615,0.694,2015-06-23 23:18:19.457000+00:00,0.447,4,5,9,43.348499,-125.545097,-3085.0
1004334,1004334,2015-06-23T23:19:03.103800Z,7D.J27D,S,0.124,63886,1004334,43.33308,-127.31240,6.0615,0.694,2015-06-23 23:18:19.457000+00:00,0.447,4,5,9,44.848900,-126.308296,-2814.8

In [16]:
type(assigned_picks_original_df.iloc[0]['time_pick'])

str

In [17]:
pick_time_str = assigned_picks_original_df.iloc[0]['time_pick']

In [18]:
pick_time_utcdatetime = UTCDateTime(pick_time_str)
pick_time_utcdatetime

2010-01-01T00:15:27.180000Z

In [20]:
starttime = pick_time_utcdatetime - 0.5
starttime

2010-01-01T00:15:26.680000Z

In [21]:
type(starttime)

obspy.core.utcdatetime.UTCDateTime

end test

In [24]:
# Randomly pick a subset of the table
n_picks = 500
assigned_picks_df = assigned_picks_original_df.iloc[:n_picks].copy()
assigned_picks_df

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,2010-01-02T18:19:35.130100Z,UW.LCW,P,-0.491,21,495,46.20482,-122.81132,41.3420,0.604,2010-01-02 18:19:24.788000+00:00,0.473,8,1,9,46.670490,-122.702011,396.0
496,496,2010-01-02T18:19:35.140100Z,UW.MTM,P,-0.399,21,496,46.20482,-122.81132,41.3420,0.604,2010-01-02 18:19:24.788000+00:00,0.473,8,1,9,46.025330,-122.212870,1121.0
497,497,2010-01-02T18:19:36.490100Z,UW.RVW,S,-0.166,21,497,46.20482,-122.81132,41.3420,0.604,2010-01-02 18:19:24.788000+00:00,0.473,8,1,9,46.149750,-122.742996,504.0
498,498,2010-01-02T19:18:22.568400Z,PB.B943,S,-0.775,22,498,47.74010,-123.12926,9.3365,0.680,2010-01-02 19:18:16.657000+00:00,0.514,0,6,6,47.813202,-122.911301,84.2
499,499,2010-01-02T19:18:22.588400Z,PB.B013,S,-0.761,22,499,47.74010,-123.12926,9.3365,0.680,2010-01-02 19:18:16.657000+00:00,0.514,0,6,6,47.813000,-122.910797,75.3

In [25]:
# Define the arguments
window_before = 0.5 # in sec
window_after = 2 # in sec
source = 'pnwstore'

freq_highpass = 2 # in Hz
new_sampling_rate = 100 # in Hz

In [ ]:
# Run the loop
amplitudes = []

for idx, row in assigned_picks_df.iterrows():

    # Define the arguments 
    date, _time = row['time'].split(' ')
    datetime_str = date+'T'+_time
    origin_time = UTCDateTime(datetime_str)  # Accept ISO string directly

    time_pick_str = row['time_pick'] 
    time_pick = UTCDateTime(time_pick_str)  # Accept ISO string directly

    network = row['station'].split('.')[0].strip()
    station = row['station'].split('.')[1].strip()
    channel = '*H*'
    starttime = time_pick - window_before 
    endtime = time_pick + window_after
   

    # # Print the number of items in amplitudes
    # print('len(amplitudes)',len(amplitudes))    

    # Request a waveform
    time.sleep(0.1)

    try:
        st = get_waveforms(network=network, station=station, channel=channel,
                            starttime=starttime, endtime=endtime,
                            source=source)
    except Exception as e:
        print(f"Request failed: {e}")

        # Save amplitude to the output DataFrame and CSV on the fly
        amp = np.nan
        amplitudes.append(amp)

        # Save skipped info to CSV
        skipped_info = {
            'network': network,
            'station': station,
            'channel': channel,
            'origin_time': origin_time,
            'time_pick': time_pick,
            'starttime': starttime,
            'endtime': endtime,
            'reason': f'Request failed: {e}'
        }
        df_skipped = pd.DataFrame([skipped_info])
        if not os.path.isfile(skipped_csv_path):
            df_skipped.to_csv(skipped_csv_path, mode='w', header=True, index=False)
        else:
            df_skipped.to_csv(skipped_csv_path, mode='a', header=False, index=False)

        continue
        

    # time.sleep(0.1)


    # Create a new stream
    sdata = Stream()
    
    # Check if loaded data have a vertical component (minimum requirement)
    has_Z = bool(st.select(id=f'{network}.{station}..??Z'))
    # Check for the presence of HH, BH, and EH channels
    has_HH = bool(st.select(id=f'{network}.{station}..HH?'))
    has_BH = bool(st.select(id=f'{network}.{station}..BH?'))
    has_EH = bool(st.select(id=f'{network}.{station}..EH?'))

    if not has_Z:
        e = f'No Vertical Component Data Present at {network}.{station} with HHZ, BHZ or EHZ channels at {time_pick_str}. Skipping'
        print(e)

        # Save amplitude in the list
        amp = np.nan
        amplitudes.append(amp)

        # Save skipped info to CSV
        skipped_info = {
            'network': network,
            'station': station,
            'channel': channel,
            'origin_time': origin_time,
            'time_pick': time_pick,
            'starttime': starttime,
            'endtime': endtime,
            'reason': f'Request failed: {e}'
        }
        df_skipped = pd.DataFrame([skipped_info])
        if not os.path.isfile(skipped_csv_path):
            df_skipped.to_csv(skipped_csv_path, mode='w', header=True, index=False)
        else:
            df_skipped.to_csv(skipped_csv_path, mode='a', header=False, index=False)

        continue

    # Apply selection logic based on channel presence
    if has_HH:
        # If all HH, BH, and EH, channels are present, select only HH
        sdata += st.select(id=f'{network}.{station}..HH*')
    elif has_BH:
        # If BH and EH channels are present, select only BH
        sdata += st.select(id=f'{network}.{station}..BH*')
    elif has_EH:
        # If only EH channels are present, select only EH
        # NTS: This may result in getting only vertical component data - EH? is used for PNSN analog stations
        # NTS: This may also be tricky for pulling full day-volumes because the sampling rate shifts for
        #      analog stations due to the remote digitization scheme used with analog stations
        sdata += st.select(id=f'{network}.{station}..EH*')
    else:
        e = f'No data available at {network}.{station} with HHZ, BHZ or EHZ channels at {time_pick_str}. Skipping.'
        print(e)

        # Save amplitude to the output DataFrame and CSV on the fly
        amp = np.nan
        amplitudes.append(amp)

        # Save skipped info to CSV
        skipped_info = {
            'network': network,
            'station': station,
            'channel': channel,
            'origin_time': origin_time,
            'time_pick': time_pick,
            'starttime': starttime,
            'endtime': endtime,
            'reason': f'Request failed: {e}'
        }
        df_skipped = pd.DataFrame([skipped_info])
        if not os.path.isfile(skipped_csv_path):
            df_skipped.to_csv(skipped_csv_path, mode='w', header=True, index=False)
        else:
            df_skipped.to_csv(skipped_csv_path, mode='a', header=False, index=False)
        continue

    # Resample
    sdata.resample(new_sampling_rate)
        
    # Apply highpass filter
    sdata.detrend(type='demean')
    sdata.taper(max_percentage=0.05)
    sdata.filter(type='highpass', freq=freq_highpass)

    max_amp = 0
    for tr in sdata:
        max_amp = max(max_amp, abs(tr.data).max())

    amplitudes.append(max_amp)

# Append to DataFrame
assigned_picks_df.loc[:,"Amplitude"] = amplitudes

assigned_picks_df.to_csv(output_csv_path, index=False)

  0%|          | 0/500 [00:00<?, ?it/s]

len(amplitudes) 0

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  0%|          | 1/500 [00:00<07:10,  1.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 1

  0%|          | 2/500 [00:01<04:03,  2.04it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  1%|          | 3/500 [00:01<02:48,  2.96it/s]

len(amplitudes) 2
len(amplitudes) 3

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  1%|          | 4/500 [00:01<02:43,  3.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 4

  1%|          | 5/500 [00:01<02:48,  2.93it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 5

  1%|          | 6/500 [00:02<02:52,  2.86it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 6

  1%|▏         | 7/500 [00:02<02:28,  3.31it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 7

  2%|▏         | 8/500 [00:02<02:19,  3.52it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 8

  2%|▏         | 9/500 [00:02<02:07,  3.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 9

  2%|▏         | 10/500 [00:03<01:59,  4.11it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  2%|▏         | 11/500 [00:03<01:50,  4.43it/s]

len(amplitudes) 10
len(amplitudes) 11

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  2%|▏         | 12/500 [00:03<01:44,  4.65it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 12

  3%|▎         | 13/500 [00:03<02:04,  3.90it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 13

  3%|▎         | 14/500 [00:04<02:17,  3.53it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 14

  3%|▎         | 15/500 [00:04<02:29,  3.25it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  3%|▎         | 16/500 [00:04<02:11,  3.67it/s]

len(amplitudes) 15
len(amplitudes) 16

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  3%|▎         | 17/500 [00:05<02:26,  3.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 17

  4%|▎         | 18/500 [00:05<02:34,  3.12it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 18

  4%|▍         | 19/500 [00:05<02:18,  3.47it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 19

  4%|▍         | 20/500 [00:06<02:28,  3.23it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 20

  4%|▍         | 21/500 [00:07<04:56,  1.62it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 21

  4%|▍         | 22/500 [00:08<05:18,  1.50it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 22

  5%|▍         | 23/500 [00:09<05:49,  1.37it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 23

  5%|▍         | 24/500 [00:09<04:37,  1.72it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 24

  5%|▌         | 25/500 [00:09<03:49,  2.07it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 25

  5%|▌         | 26/500 [00:09<03:16,  2.42it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 26

  5%|▌         | 27/500 [00:10<03:22,  2.34it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 27

  6%|▌         | 28/500 [00:10<03:24,  2.31it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 28

  6%|▌         | 29/500 [00:11<03:00,  2.61it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 29

  6%|▌         | 30/500 [00:11<03:00,  2.60it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 30

  6%|▌         | 31/500 [00:11<03:07,  2.50it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 31

  6%|▋         | 32/500 [00:12<03:20,  2.34it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  7%|▋         | 33/500 [00:12<02:42,  2.88it/s]

len(amplitudes) 32
len(amplitudes) 33

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  7%|▋         | 34/500 [00:12<02:12,  3.51it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 34

  7%|▋         | 35/500 [00:12<02:01,  3.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 35

  7%|▋         | 36/500 [00:13<01:53,  4.08it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  7%|▋         | 37/500 [00:13<01:43,  4.47it/s]

len(amplitudes) 36
len(amplitudes) 37

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  8%|▊         | 38/500 [00:13<01:41,  4.57it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  8%|▊         | 39/500 [00:13<01:29,  5.15it/s]

len(amplitudes) 38
len(amplitudes) 39

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  8%|▊         | 40/500 [00:13<01:30,  5.07it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 40

  8%|▊         | 41/500 [00:13<01:31,  5.00it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 41

  8%|▊         | 42/500 [00:14<01:33,  4.90it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 42

  9%|▊         | 43/500 [00:14<01:33,  4.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  9%|▉         | 44/500 [00:14<01:23,  5.45it/s]

len(amplitudes) 43
len(amplitudes) 44

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  9%|▉         | 45/500 [00:14<01:26,  5.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  9%|▉         | 46/500 [00:14<01:18,  5.82it/s]

len(amplitudes) 45
len(amplitudes) 46

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
  9%|▉         | 47/500 [00:15<01:29,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 47

 10%|▉         | 48/500 [00:15<02:07,  3.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 48

 10%|▉         | 49/500 [00:15<02:03,  3.65it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 49

 10%|█         | 50/500 [00:16<01:53,  3.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 10%|█         | 51/500 [00:16<01:36,  4.64it/s]

len(amplitudes) 50
len(amplitudes) 51

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 10%|█         | 52/500 [00:16<01:43,  4.31it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 52

 11%|█         | 53/500 [00:16<01:46,  4.19it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 11%|█         | 54/500 [00:16<01:33,  4.78it/s]

len(amplitudes) 53
len(amplitudes) 54

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 11%|█         | 55/500 [00:17<01:32,  4.83it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 55

 11%|█         | 56/500 [00:17<01:31,  4.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 11%|█▏        | 57/500 [00:17<01:22,  5.35it/s]

len(amplitudes) 56
len(amplitudes) 57

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 12%|█▏        | 58/500 [00:17<01:16,  5.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 58

 12%|█▏        | 59/500 [00:17<01:27,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 59

 12%|█▏        | 60/500 [00:17<01:28,  4.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 60

 12%|█▏        | 61/500 [00:18<01:28,  4.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 61

 12%|█▏        | 62/500 [00:18<01:29,  4.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 62

 13%|█▎        | 63/500 [00:18<01:30,  4.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 63

 13%|█▎        | 64/500 [00:18<01:30,  4.83it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 13%|█▎        | 65/500 [00:18<01:21,  5.35it/s]

len(amplitudes) 64
len(amplitudes) 65

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 13%|█▎        | 66/500 [00:19<01:23,  5.20it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 66

 13%|█▎        | 67/500 [00:19<01:25,  5.08it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 67

 14%|█▎        | 68/500 [00:19<01:26,  5.02it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 14%|█▍        | 69/500 [00:19<01:17,  5.55it/s]

len(amplitudes) 68
len(amplitudes) 69

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 14%|█▍        | 70/500 [00:19<01:21,  5.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 14%|█▍        | 71/500 [00:20<01:13,  5.82it/s]

len(amplitudes) 70
len(amplitudes) 71

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 14%|█▍        | 72/500 [00:20<01:08,  6.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 72

 15%|█▍        | 73/500 [00:20<01:14,  5.74it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 73

 15%|█▍        | 74/500 [00:20<01:18,  5.42it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 15%|█▌        | 75/500 [00:20<01:17,  5.50it/s]

len(amplitudes) 74
len(amplitudes) 75

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 15%|█▌        | 76/500 [00:20<01:12,  5.87it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 76

 15%|█▌        | 77/500 [00:21<01:16,  5.51it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 77

 16%|█▌        | 78/500 [00:21<01:20,  5.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 78

 16%|█▌        | 79/500 [00:21<01:44,  4.02it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 16%|█▌        | 80/500 [00:21<01:30,  4.63it/s]

len(amplitudes) 79
len(amplitudes) 80

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 16%|█▌        | 81/500 [00:22<01:29,  4.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 81

 16%|█▋        | 82/500 [00:22<01:29,  4.66it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 17%|█▋        | 83/500 [00:22<01:18,  5.29it/s]

len(amplitudes) 82
len(amplitudes) 83

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 17%|█▋        | 84/500 [00:22<01:13,  5.69it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 17%|█▋        | 85/500 [00:22<01:07,  6.11it/s]

len(amplitudes) 84
len(amplitudes) 85

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 17%|█▋        | 86/500 [00:22<01:04,  6.38it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 86

 17%|█▋        | 87/500 [00:23<01:10,  5.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 87

 18%|█▊        | 88/500 [00:23<01:15,  5.49it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 88

 18%|█▊        | 89/500 [00:23<01:17,  5.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 89

 18%|█▊        | 90/500 [00:23<01:26,  4.77it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 18%|█▊        | 91/500 [00:23<01:17,  5.29it/s]

len(amplitudes) 90
len(amplitudes) 91

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 18%|█▊        | 92/500 [00:24<01:19,  5.13it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 92

 19%|█▊        | 93/500 [00:24<01:21,  5.02it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 93

 19%|█▉        | 94/500 [00:24<01:21,  4.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 94

 19%|█▉        | 95/500 [00:24<01:22,  4.91it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 95

 19%|█▉        | 96/500 [00:24<01:22,  4.90it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 96

 19%|█▉        | 97/500 [00:25<01:23,  4.83it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 20%|█▉        | 98/500 [00:25<01:14,  5.40it/s]

len(amplitudes) 97
len(amplitudes) 98

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 20%|█▉        | 99/500 [00:25<01:16,  5.24it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 20%|██        | 100/500 [00:25<01:09,  5.79it/s]

len(amplitudes) 99
len(amplitudes) 100

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 20%|██        | 101/500 [00:25<01:04,  6.14it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 101

 20%|██        | 102/500 [00:25<01:10,  5.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 102

 21%|██        | 103/500 [00:26<01:13,  5.39it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 103

 21%|██        | 104/500 [00:26<01:15,  5.23it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 104

 21%|██        | 105/500 [00:26<01:17,  5.12it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 105

 21%|██        | 106/500 [00:26<01:18,  5.01it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 106

 21%|██▏       | 107/500 [00:26<01:20,  4.91it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 107

 22%|██▏       | 108/500 [00:27<01:19,  4.91it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 22%|██▏       | 109/500 [00:27<01:10,  5.52it/s]

len(amplitudes) 108
len(amplitudes) 109

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 22%|██▏       | 110/500 [00:27<01:05,  5.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 110

 22%|██▏       | 111/500 [00:27<01:16,  5.11it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 111

 22%|██▏       | 112/500 [00:28<01:34,  4.09it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 23%|██▎       | 113/500 [00:28<01:22,  4.67it/s]

len(amplitudes) 112
len(amplitudes) 113

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 23%|██▎       | 114/500 [00:28<01:21,  4.74it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 114

 23%|██▎       | 115/500 [00:28<01:21,  4.75it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 115

 23%|██▎       | 116/500 [00:28<01:27,  4.41it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 116

 23%|██▎       | 117/500 [00:29<01:31,  4.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 24%|██▎       | 118/500 [00:29<01:19,  4.79it/s]

len(amplitudes) 117
len(amplitudes) 118

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 24%|██▍       | 119/500 [00:29<01:18,  4.84it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 24%|██▍       | 120/500 [00:29<01:11,  5.34it/s]

len(amplitudes) 119
len(amplitudes) 120

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 24%|██▍       | 121/500 [00:29<01:05,  5.77it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 121

 24%|██▍       | 122/500 [00:29<01:09,  5.47it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 25%|██▍       | 123/500 [00:30<01:04,  5.82it/s]

len(amplitudes) 122
len(amplitudes) 123

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 25%|██▍       | 124/500 [00:30<01:01,  6.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 124

 25%|██▌       | 125/500 [00:30<01:06,  5.61it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 25%|██▌       | 126/500 [00:30<01:03,  5.92it/s]

len(amplitudes) 125
len(amplitudes) 126

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 25%|██▌       | 127/500 [00:30<01:07,  5.54it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 26%|██▌       | 128/500 [00:30<01:05,  5.70it/s]

len(amplitudes) 127
len(amplitudes) 128

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 26%|██▌       | 129/500 [00:31<01:08,  5.40it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 129

 26%|██▌       | 130/500 [00:31<01:41,  3.63it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 26%|██▌       | 131/500 [00:31<01:27,  4.23it/s]

len(amplitudes) 130
len(amplitudes) 131

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 26%|██▋       | 132/500 [00:31<01:18,  4.67it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 27%|██▋       | 133/500 [00:32<01:10,  5.20it/s]

len(amplitudes) 132
len(amplitudes) 133

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 27%|██▋       | 134/500 [00:32<01:11,  5.09it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 134

 27%|██▋       | 135/500 [00:32<01:13,  4.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 27%|██▋       | 136/500 [00:32<01:06,  5.49it/s]

len(amplitudes) 135
len(amplitudes) 136

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 27%|██▋       | 137/500 [00:32<01:08,  5.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 28%|██▊       | 138/500 [00:33<01:03,  5.72it/s]

len(amplitudes) 137
len(amplitudes) 138

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 28%|██▊       | 139/500 [00:33<00:59,  6.07it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 28%|██▊       | 140/500 [00:33<00:57,  6.31it/s]

len(amplitudes) 139
len(amplitudes) 140

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 28%|██▊       | 141/500 [00:33<01:02,  5.79it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 28%|██▊       | 142/500 [00:33<00:58,  6.08it/s]

len(amplitudes) 141
len(amplitudes) 142

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 29%|██▊       | 143/500 [00:33<01:03,  5.58it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 143

 29%|██▉       | 144/500 [00:34<01:07,  5.31it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 144

 29%|██▉       | 145/500 [00:34<01:09,  5.14it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 145

 29%|██▉       | 146/500 [00:34<01:10,  5.00it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 29%|██▉       | 147/500 [00:34<01:08,  5.18it/s]

len(amplitudes) 146
len(amplitudes) 147

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 30%|██▉       | 148/500 [00:34<01:09,  5.04it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 148

 30%|██▉       | 149/500 [00:35<01:10,  4.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 30%|███       | 150/500 [00:35<01:03,  5.47it/s]

len(amplitudes) 149
len(amplitudes) 150

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 30%|███       | 151/500 [00:35<01:07,  5.15it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 151

 30%|███       | 152/500 [00:35<01:08,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 31%|███       | 153/500 [00:35<01:02,  5.51it/s]

len(amplitudes) 152
len(amplitudes) 153

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 31%|███       | 154/500 [00:36<01:05,  5.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 154

 31%|███       | 155/500 [00:36<01:07,  5.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 155

 31%|███       | 156/500 [00:36<01:08,  5.00it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 156

 31%|███▏      | 157/500 [00:36<01:09,  4.92it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 157

 32%|███▏      | 158/500 [00:37<01:23,  4.09it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 158

 32%|███▏      | 159/500 [00:37<01:19,  4.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 32%|███▏      | 160/500 [00:37<01:11,  4.73it/s]

len(amplitudes) 159
len(amplitudes) 160

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 32%|███▏      | 161/500 [00:37<01:11,  4.76it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 32%|███▏      | 162/500 [00:37<01:03,  5.33it/s]

len(amplitudes) 161
len(amplitudes) 162

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 33%|███▎      | 163/500 [00:37<00:57,  5.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 33%|███▎      | 164/500 [00:37<00:53,  6.31it/s]

len(amplitudes) 163
len(amplitudes) 164

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 33%|███▎      | 165/500 [00:38<00:50,  6.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 33%|███▎      | 166/500 [00:38<00:48,  6.89it/s]

len(amplitudes) 165
len(amplitudes) 166

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 33%|███▎      | 167/500 [00:38<00:55,  6.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 167

 34%|███▎      | 168/500 [00:38<00:59,  5.62it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 34%|███▍      | 169/500 [00:38<00:55,  6.00it/s]

len(amplitudes) 168
len(amplitudes) 169

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 34%|███▍      | 170/500 [00:39<00:58,  5.62it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 170

 34%|███▍      | 171/500 [00:39<01:01,  5.34it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 34%|███▍      | 172/500 [00:39<00:56,  5.84it/s]

len(amplitudes) 171
len(amplitudes) 172

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 35%|███▍      | 173/500 [00:39<00:59,  5.48it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 173

 35%|███▍      | 174/500 [00:39<01:02,  5.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 174

 35%|███▌      | 175/500 [00:39<01:03,  5.14it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 35%|███▌      | 176/500 [00:40<00:56,  5.72it/s]

len(amplitudes) 175
len(amplitudes) 176

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 35%|███▌      | 177/500 [00:40<00:54,  5.90it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 177

 36%|███▌      | 178/500 [00:40<00:58,  5.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 36%|███▌      | 179/500 [00:40<00:53,  6.01it/s]

len(amplitudes) 178
len(amplitudes) 179

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 36%|███▌      | 180/500 [00:40<00:49,  6.44it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 180

 36%|███▌      | 181/500 [00:41<01:20,  3.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 36%|███▋      | 182/500 [00:41<01:08,  4.63it/s]

len(amplitudes) 181
len(amplitudes) 182

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 37%|███▋      | 183/500 [00:41<01:02,  5.04it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 37%|███▋      | 184/500 [00:41<00:56,  5.57it/s]

len(amplitudes) 183
len(amplitudes) 184

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 37%|███▋      | 185/500 [00:41<00:51,  6.08it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 37%|███▋      | 186/500 [00:41<00:48,  6.52it/s]

len(amplitudes) 185
len(amplitudes) 186

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 37%|███▋      | 187/500 [00:42<01:01,  5.12it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 187

 38%|███▊      | 188/500 [00:42<01:01,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 38%|███▊      | 189/500 [00:42<00:56,  5.54it/s]

len(amplitudes) 188
len(amplitudes) 189

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 38%|███▊      | 190/500 [00:42<00:58,  5.31it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 190

 38%|███▊      | 191/500 [00:42<00:59,  5.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 191

 38%|███▊      | 192/500 [00:43<01:00,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 192

 39%|███▊      | 193/500 [00:43<01:04,  4.79it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 39%|███▉      | 194/500 [00:43<00:56,  5.41it/s]

len(amplitudes) 193
len(amplitudes) 194

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 39%|███▉      | 195/500 [00:43<00:53,  5.67it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 39%|███▉      | 196/500 [00:43<00:49,  6.16it/s]

len(amplitudes) 195
len(amplitudes) 196

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 39%|███▉      | 197/500 [00:43<00:45,  6.59it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 40%|███▉      | 198/500 [00:44<00:44,  6.72it/s]

len(amplitudes) 197
len(amplitudes) 198

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 40%|███▉      | 199/500 [00:44<00:49,  6.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 40%|████      | 200/500 [00:44<00:47,  6.34it/s]

len(amplitudes) 199
len(amplitudes) 200

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 40%|████      | 201/500 [00:44<00:51,  5.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 201

 40%|████      | 202/500 [00:44<00:54,  5.50it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 202

 41%|████      | 203/500 [00:45<00:56,  5.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 203

 41%|████      | 204/500 [00:45<00:57,  5.13it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 204

 41%|████      | 205/500 [00:45<00:58,  5.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 41%|████      | 206/500 [00:45<00:52,  5.63it/s]

len(amplitudes) 205
len(amplitudes) 206

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 41%|████▏     | 207/500 [00:45<00:48,  6.00it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 42%|████▏     | 208/500 [00:45<00:46,  6.25it/s]

len(amplitudes) 207
len(amplitudes) 208

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 42%|████▏     | 209/500 [00:45<00:44,  6.57it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 42%|████▏     | 210/500 [00:46<00:42,  6.89it/s]

len(amplitudes) 209
len(amplitudes) 210

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 42%|████▏     | 211/500 [00:46<00:40,  7.15it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 42%|████▏     | 212/500 [00:46<00:41,  6.90it/s]

len(amplitudes) 211
len(amplitudes) 212

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 43%|████▎     | 213/500 [00:46<00:40,  7.04it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 43%|████▎     | 214/500 [00:46<00:40,  7.04it/s]

len(amplitudes) 213
len(amplitudes) 214

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 43%|████▎     | 215/500 [00:46<00:39,  7.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 43%|████▎     | 216/500 [00:46<00:38,  7.36it/s]

len(amplitudes) 215
len(amplitudes) 216

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 43%|████▎     | 217/500 [00:47<00:40,  7.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 217

 44%|████▎     | 218/500 [00:47<00:47,  5.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 218

 44%|████▍     | 219/500 [00:47<01:07,  4.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 219

 44%|████▍     | 220/500 [00:48<01:18,  3.56it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 220

 44%|████▍     | 221/500 [00:48<01:26,  3.24it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 44%|████▍     | 222/500 [00:48<01:11,  3.90it/s]

len(amplitudes) 221
len(amplitudes) 222

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 45%|████▍     | 223/500 [00:48<01:07,  4.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 223

 45%|████▍     | 224/500 [00:49<01:09,  3.99it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 224

 45%|████▌     | 225/500 [00:49<01:07,  4.06it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 225

 45%|████▌     | 226/500 [00:49<01:19,  3.44it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 226

 45%|████▌     | 227/500 [00:50<01:26,  3.15it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 227

 46%|████▌     | 228/500 [00:50<01:19,  3.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 46%|████▌     | 229/500 [00:50<01:06,  4.08it/s]

len(amplitudes) 228
len(amplitudes) 229

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 46%|████▌     | 230/500 [00:50<01:03,  4.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 230

 46%|████▌     | 231/500 [00:50<01:00,  4.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 231

 46%|████▋     | 232/500 [00:51<01:01,  4.35it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 232

 47%|████▋     | 233/500 [00:51<01:03,  4.23it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 233

 47%|████▋     | 234/500 [00:51<01:21,  3.25it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 234

 47%|████▋     | 235/500 [00:52<01:34,  2.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 235

 47%|████▋     | 236/500 [00:52<01:48,  2.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 236

 47%|████▋     | 237/500 [00:53<01:46,  2.46it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 237

 48%|████▊     | 238/500 [00:53<01:47,  2.44it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 238

 48%|████▊     | 239/500 [00:53<01:31,  2.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 239

 48%|████▊     | 240/500 [00:54<01:20,  3.23it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 240

 48%|████▊     | 241/500 [00:54<01:12,  3.56it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 241

 48%|████▊     | 242/500 [00:54<01:07,  3.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 49%|████▊     | 243/500 [00:54<01:01,  4.18it/s]

len(amplitudes) 242
len(amplitudes) 243

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 49%|████▉     | 244/500 [00:54<00:59,  4.34it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 244

 49%|████▉     | 245/500 [00:55<01:10,  3.64it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 245

 49%|████▉     | 246/500 [00:55<01:18,  3.23it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 49%|████▉     | 247/500 [00:55<01:05,  3.85it/s]

len(amplitudes) 246
len(amplitudes) 247

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 50%|████▉     | 248/500 [00:55<00:56,  4.50it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 248

 50%|████▉     | 249/500 [00:56<00:54,  4.60it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 249

 50%|█████     | 250/500 [00:56<00:56,  4.42it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 250

 50%|█████     | 251/500 [00:56<00:56,  4.38it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 251

 50%|█████     | 252/500 [00:56<00:55,  4.48it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 252

 51%|█████     | 253/500 [00:57<01:06,  3.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 253

 51%|█████     | 254/500 [00:57<01:14,  3.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 254

 51%|█████     | 255/500 [00:57<01:07,  3.61it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 255

 51%|█████     | 256/500 [00:58<01:17,  3.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 256

 51%|█████▏    | 257/500 [00:58<01:09,  3.49it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 257

 52%|█████▏    | 258/500 [00:58<01:04,  3.76it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 258

 52%|█████▏    | 259/500 [00:58<01:01,  3.91it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 259

 52%|█████▏    | 260/500 [00:59<00:58,  4.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 260

 52%|█████▏    | 261/500 [00:59<00:55,  4.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 261

 52%|█████▏    | 262/500 [00:59<01:04,  3.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 262

 53%|█████▎    | 263/500 [00:59<00:59,  3.96it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 263

 53%|█████▎    | 264/500 [01:00<00:56,  4.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 53%|█████▎    | 265/500 [01:00<00:49,  4.77it/s]

len(amplitudes) 264
len(amplitudes) 265

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 53%|█████▎    | 266/500 [01:00<00:44,  5.29it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 266

 53%|█████▎    | 267/500 [01:00<00:45,  5.15it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 267

 54%|█████▎    | 268/500 [01:00<00:48,  4.81it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 54%|█████▍    | 269/500 [01:01<00:43,  5.31it/s]

len(amplitudes) 268
len(amplitudes) 269

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 54%|█████▍    | 270/500 [01:01<00:39,  5.79it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 270

 54%|█████▍    | 271/500 [01:01<00:41,  5.49it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 54%|█████▍    | 272/500 [01:01<00:42,  5.33it/s]

len(amplitudes) 271
len(amplitudes) 272

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 55%|█████▍    | 273/500 [01:01<00:45,  5.00it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 55%|█████▍    | 274/500 [01:01<00:40,  5.53it/s]

len(amplitudes) 273
len(amplitudes) 274

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 55%|█████▌    | 275/500 [01:02<00:46,  4.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 275

 55%|█████▌    | 276/500 [01:02<00:59,  3.74it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 276

 55%|█████▌    | 277/500 [01:02<00:56,  3.98it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 56%|█████▌    | 278/500 [01:02<00:51,  4.32it/s]

len(amplitudes) 277
len(amplitudes) 278

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 56%|█████▌    | 279/500 [01:03<00:50,  4.42it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 279

 56%|█████▌    | 280/500 [01:03<00:48,  4.49it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 280

 56%|█████▌    | 281/500 [01:03<00:48,  4.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 281

 56%|█████▋    | 282/500 [01:03<00:47,  4.58it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 57%|█████▋    | 283/500 [01:04<00:45,  4.78it/s]

len(amplitudes) 282
len(amplitudes) 283

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 57%|█████▋    | 284/500 [01:04<00:45,  4.75it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 284

 57%|█████▋    | 285/500 [01:04<00:45,  4.72it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 285

 57%|█████▋    | 286/500 [01:04<00:45,  4.71it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 286

 57%|█████▋    | 287/500 [01:04<00:45,  4.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 58%|█████▊    | 288/500 [01:05<00:41,  5.16it/s]

len(amplitudes) 287
len(amplitudes) 288

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 58%|█████▊    | 289/500 [01:05<00:50,  4.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 58%|█████▊    | 290/500 [01:05<00:44,  4.77it/s]

len(amplitudes) 289
len(amplitudes) 290

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 58%|█████▊    | 291/500 [01:05<00:43,  4.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 291

 58%|█████▊    | 292/500 [01:05<00:42,  4.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 59%|█████▊    | 293/500 [01:06<00:38,  5.41it/s]

len(amplitudes) 292
len(amplitudes) 293

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 59%|█████▉    | 294/500 [01:06<00:39,  5.24it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 294

 59%|█████▉    | 295/500 [01:06<00:43,  4.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 59%|█████▉    | 296/500 [01:06<00:39,  5.20it/s]

len(amplitudes) 295
len(amplitudes) 296

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 59%|█████▉    | 297/500 [01:06<00:35,  5.69it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 297

 60%|█████▉    | 298/500 [01:07<00:37,  5.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 298

 60%|█████▉    | 299/500 [01:07<00:38,  5.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 60%|██████    | 300/500 [01:07<00:34,  5.78it/s]

len(amplitudes) 299
len(amplitudes) 300

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 60%|██████    | 301/500 [01:07<00:36,  5.48it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 301

 60%|██████    | 302/500 [01:07<00:42,  4.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 302

 61%|██████    | 303/500 [01:08<00:41,  4.72it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 303

 61%|██████    | 304/500 [01:08<00:42,  4.60it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 304

 61%|██████    | 305/500 [01:08<00:53,  3.67it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 305

 61%|██████    | 306/500 [01:08<00:53,  3.60it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 61%|██████▏   | 307/500 [01:09<00:45,  4.25it/s]

len(amplitudes) 306
len(amplitudes) 307

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 62%|██████▏   | 308/500 [01:09<00:43,  4.36it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 62%|██████▏   | 309/500 [01:09<00:38,  4.98it/s]

len(amplitudes) 308
len(amplitudes) 309

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 62%|██████▏   | 310/500 [01:09<00:34,  5.51it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 310

 62%|██████▏   | 311/500 [01:09<00:45,  4.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 311

 62%|██████▏   | 312/500 [01:10<00:43,  4.27it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 63%|██████▎   | 313/500 [01:10<00:38,  4.84it/s]

len(amplitudes) 312
len(amplitudes) 313

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 63%|██████▎   | 314/500 [01:10<00:38,  4.87it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 314

 63%|██████▎   | 315/500 [01:10<00:37,  4.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 63%|██████▎   | 316/500 [01:10<00:34,  5.36it/s]

len(amplitudes) 315
len(amplitudes) 316

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 63%|██████▎   | 317/500 [01:11<00:35,  5.20it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 317

 64%|██████▎   | 318/500 [01:11<00:35,  5.08it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 64%|██████▍   | 319/500 [01:11<00:32,  5.55it/s]

len(amplitudes) 318
len(amplitudes) 319

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 64%|██████▍   | 320/500 [01:11<00:34,  5.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 64%|██████▍   | 321/500 [01:11<00:32,  5.52it/s]

len(amplitudes) 320
len(amplitudes) 321

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 64%|██████▍   | 322/500 [01:11<00:29,  5.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 65%|██████▍   | 323/500 [01:12<00:27,  6.34it/s]

len(amplitudes) 322
len(amplitudes) 323

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 65%|██████▍   | 324/500 [01:12<00:30,  5.74it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 65%|██████▌   | 325/500 [01:12<00:28,  6.13it/s]

len(amplitudes) 324
len(amplitudes) 325

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 65%|██████▌   | 326/500 [01:12<00:30,  5.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 65%|██████▌   | 327/500 [01:12<00:28,  6.09it/s]

len(amplitudes) 326
len(amplitudes) 327

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 66%|██████▌   | 328/500 [01:12<00:30,  5.68it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 328

 66%|██████▌   | 329/500 [01:13<00:31,  5.44it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 329

 66%|██████▌   | 330/500 [01:13<00:33,  5.02it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 66%|██████▌   | 331/500 [01:13<00:30,  5.51it/s]

len(amplitudes) 330
len(amplitudes) 331

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 66%|██████▋   | 332/500 [01:13<00:28,  5.89it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 332

 67%|██████▋   | 333/500 [01:13<00:30,  5.54it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 333

 67%|██████▋   | 334/500 [01:14<00:31,  5.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 334

 67%|██████▋   | 335/500 [01:14<00:32,  5.14it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 335

 67%|██████▋   | 336/500 [01:14<00:32,  5.03it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 67%|██████▋   | 337/500 [01:14<00:29,  5.51it/s]

len(amplitudes) 336
len(amplitudes) 337

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 68%|██████▊   | 338/500 [01:14<00:27,  5.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 338

 68%|██████▊   | 339/500 [01:15<00:33,  4.79it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 339

 68%|██████▊   | 340/500 [01:15<00:33,  4.77it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 340

 68%|██████▊   | 341/500 [01:15<00:33,  4.78it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 341

 68%|██████▊   | 342/500 [01:15<00:33,  4.76it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 342

 69%|██████▊   | 343/500 [01:15<00:33,  4.72it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 69%|██████▉   | 344/500 [01:16<00:29,  5.32it/s]

len(amplitudes) 343
len(amplitudes) 344

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 69%|██████▉   | 345/500 [01:16<00:27,  5.56it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 345

 69%|██████▉   | 346/500 [01:16<00:28,  5.34it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 69%|██████▉   | 347/500 [01:16<00:25,  5.90it/s]

len(amplitudes) 346
len(amplitudes) 347

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 70%|██████▉   | 348/500 [01:16<00:28,  5.25it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 348

 70%|██████▉   | 349/500 [01:17<00:29,  5.12it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 349

 70%|███████   | 350/500 [01:17<00:29,  5.01it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 70%|███████   | 351/500 [01:17<00:28,  5.19it/s]

len(amplitudes) 350
len(amplitudes) 351

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 70%|███████   | 352/500 [01:17<00:26,  5.61it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 71%|███████   | 353/500 [01:17<00:24,  6.05it/s]

len(amplitudes) 352
len(amplitudes) 353

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 71%|███████   | 354/500 [01:17<00:25,  5.63it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 71%|███████   | 355/500 [01:18<00:23,  6.07it/s]

len(amplitudes) 354
len(amplitudes) 355

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 71%|███████   | 356/500 [01:18<00:25,  5.57it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 71%|███████▏  | 357/500 [01:18<00:24,  5.76it/s]

len(amplitudes) 356
len(amplitudes) 357

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 72%|███████▏  | 358/500 [01:18<00:23,  6.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 358

 72%|███████▏  | 359/500 [01:18<00:24,  5.72it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 359

 72%|███████▏  | 360/500 [01:18<00:25,  5.47it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 72%|███████▏  | 361/500 [01:19<00:23,  5.94it/s]

len(amplitudes) 360
len(amplitudes) 361

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 72%|███████▏  | 362/500 [01:19<00:24,  5.54it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 362

 73%|███████▎  | 363/500 [01:19<00:26,  5.27it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 73%|███████▎  | 364/500 [01:19<00:25,  5.32it/s]

len(amplitudes) 363
len(amplitudes) 364

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 73%|███████▎  | 365/500 [01:19<00:26,  5.08it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 365

 73%|███████▎  | 366/500 [01:20<00:27,  4.96it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 366

 73%|███████▎  | 367/500 [01:20<00:27,  4.87it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 367

 74%|███████▎  | 368/500 [01:20<00:27,  4.81it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 74%|███████▍  | 369/500 [01:20<00:26,  4.96it/s]

len(amplitudes) 368
len(amplitudes) 369

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 74%|███████▍  | 370/500 [01:20<00:26,  4.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 74%|███████▍  | 371/500 [01:21<00:24,  5.33it/s]

len(amplitudes) 370
len(amplitudes) 371

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 74%|███████▍  | 372/500 [01:21<00:25,  5.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 372

 75%|███████▍  | 373/500 [01:21<00:25,  5.04it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 373

 75%|███████▍  | 374/500 [01:21<00:25,  4.93it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 75%|███████▌  | 375/500 [01:21<00:23,  5.43it/s]

len(amplitudes) 374
len(amplitudes) 375

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 75%|███████▌  | 376/500 [01:22<00:21,  5.89it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 376

 75%|███████▌  | 377/500 [01:22<00:22,  5.56it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 76%|███████▌  | 378/500 [01:22<00:22,  5.37it/s]

len(amplitudes) 377

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 378

 76%|███████▌  | 379/500 [01:22<00:23,  5.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 379

 76%|███████▌  | 380/500 [01:22<00:23,  5.06it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 76%|███████▌  | 381/500 [01:22<00:21,  5.54it/s]

len(amplitudes) 380
len(amplitudes) 381

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 76%|███████▋  | 382/500 [01:23<00:19,  6.00it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 77%|███████▋  | 383/500 [01:23<00:18,  6.37it/s]

len(amplitudes) 382
len(amplitudes) 383

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 77%|███████▋  | 384/500 [01:23<00:20,  5.76it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 384

 77%|███████▋  | 385/500 [01:23<00:21,  5.43it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 385

 77%|███████▋  | 386/500 [01:23<00:21,  5.22it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 77%|███████▋  | 387/500 [01:24<00:19,  5.67it/s]

len(amplitudes) 386
len(amplitudes) 387

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 78%|███████▊  | 388/500 [01:24<00:18,  6.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 388

 78%|███████▊  | 389/500 [01:24<00:19,  5.59it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 389

 78%|███████▊  | 390/500 [01:24<00:20,  5.29it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 78%|███████▊  | 391/500 [01:24<00:18,  5.77it/s]

len(amplitudes) 390
len(amplitudes) 391

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 78%|███████▊  | 392/500 [01:24<00:17,  6.16it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 79%|███████▊  | 393/500 [01:24<00:16,  6.50it/s]

len(amplitudes) 392
len(amplitudes) 393

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 79%|███████▉  | 394/500 [01:25<00:18,  5.83it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 394

 79%|███████▉  | 395/500 [01:25<00:19,  5.51it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 395

 79%|███████▉  | 396/500 [01:25<00:19,  5.30it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 396

 79%|███████▉  | 397/500 [01:25<00:19,  5.19it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 397

 80%|███████▉  | 398/500 [01:26<00:20,  5.04it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 80%|███████▉  | 399/500 [01:26<00:18,  5.55it/s]

len(amplitudes) 398
len(amplitudes) 399

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 80%|████████  | 400/500 [01:26<00:16,  5.99it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 80%|████████  | 401/500 [01:26<00:15,  6.37it/s]

len(amplitudes) 400
len(amplitudes) 401

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 80%|████████  | 402/500 [01:26<00:17,  5.75it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 402

 81%|████████  | 403/500 [01:26<00:17,  5.47it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 403

 81%|████████  | 404/500 [01:27<00:18,  5.26it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 81%|████████  | 405/500 [01:27<00:18,  5.18it/s]

len(amplitudes) 404
len(amplitudes) 405

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 81%|████████  | 406/500 [01:27<00:18,  5.08it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 81%|████████▏ | 407/500 [01:27<00:16,  5.54it/s]

len(amplitudes) 406
len(amplitudes) 407

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 82%|████████▏ | 408/500 [01:27<00:19,  4.77it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 82%|████████▏ | 409/500 [01:28<00:17,  5.14it/s]

len(amplitudes) 408
len(amplitudes) 409

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 82%|████████▏ | 410/500 [01:28<00:17,  5.05it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 82%|████████▏ | 411/500 [01:28<00:16,  5.55it/s]

len(amplitudes) 410
len(amplitudes) 411

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 82%|████████▏ | 412/500 [01:28<00:16,  5.38it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 83%|████████▎ | 413/500 [01:28<00:14,  5.84it/s]

len(amplitudes) 412
len(amplitudes) 413

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 83%|████████▎ | 414/500 [01:28<00:13,  6.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 414

 83%|████████▎ | 415/500 [01:29<00:15,  5.48it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 415

 83%|████████▎ | 416/500 [01:29<00:16,  5.22it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 416

 83%|████████▎ | 417/500 [01:29<00:18,  4.60it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 84%|████████▎ | 418/500 [01:29<00:15,  5.20it/s]

len(amplitudes) 417
len(amplitudes) 418

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 84%|████████▍ | 419/500 [01:29<00:14,  5.64it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 84%|████████▍ | 420/500 [01:29<00:13,  6.06it/s]

len(amplitudes) 419
len(amplitudes) 420

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 84%|████████▍ | 421/500 [01:30<00:13,  5.67it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 84%|████████▍ | 422/500 [01:30<00:13,  5.99it/s]

len(amplitudes) 421
len(amplitudes) 422

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 85%|████████▍ | 423/500 [01:30<00:12,  6.29it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 423

 85%|████████▍ | 424/500 [01:30<00:13,  5.71it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 85%|████████▌ | 425/500 [01:30<00:12,  6.01it/s]

len(amplitudes) 424
len(amplitudes) 425

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 85%|████████▌ | 426/500 [01:31<00:14,  5.12it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 426

 85%|████████▌ | 427/500 [01:31<00:18,  3.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 427

 86%|████████▌ | 428/500 [01:31<00:17,  4.10it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 428

 86%|████████▌ | 429/500 [01:31<00:17,  3.95it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 429

 86%|████████▌ | 430/500 [01:32<00:16,  4.17it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 86%|████████▌ | 431/500 [01:32<00:14,  4.79it/s]

len(amplitudes) 430
len(amplitudes) 431

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 86%|████████▋ | 432/500 [01:32<00:14,  4.59it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 87%|████████▋ | 433/500 [01:32<00:13,  4.96it/s]

len(amplitudes) 432
len(amplitudes) 433

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 87%|████████▋ | 434/500 [01:33<00:18,  3.51it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 434

 87%|████████▋ | 435/500 [01:33<00:23,  2.80it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 435

 87%|████████▋ | 436/500 [01:34<00:28,  2.27it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 436

 87%|████████▋ | 437/500 [01:34<00:24,  2.62it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 437

 88%|████████▊ | 438/500 [01:35<00:25,  2.42it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 438

 88%|████████▊ | 439/500 [01:35<00:26,  2.34it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 439

 88%|████████▊ | 440/500 [01:35<00:21,  2.77it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 440

 88%|████████▊ | 441/500 [01:36<00:20,  2.94it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 441

 88%|████████▊ | 442/500 [01:36<00:22,  2.56it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 89%|████████▊ | 443/500 [01:36<00:18,  3.16it/s]

len(amplitudes) 442
len(amplitudes) 443

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 89%|████████▉ | 444/500 [01:36<00:14,  3.82it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 89%|████████▉ | 445/500 [01:36<00:12,  4.44it/s]

len(amplitudes) 444
len(amplitudes) 445

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 89%|████████▉ | 446/500 [01:37<00:11,  4.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 446

 89%|████████▉ | 447/500 [01:37<00:15,  3.47it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 447

 90%|████████▉ | 448/500 [01:38<00:17,  2.98it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 448

 90%|████████▉ | 449/500 [01:38<00:15,  3.36it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 449

 90%|█████████ | 450/500 [01:38<00:17,  2.85it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 450

 90%|█████████ | 451/500 [01:39<00:17,  2.76it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 451

 90%|█████████ | 452/500 [01:39<00:16,  2.84it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 91%|█████████ | 453/500 [01:39<00:13,  3.47it/s]

len(amplitudes) 452
len(amplitudes) 453

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 91%|█████████ | 454/500 [01:39<00:12,  3.64it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 91%|█████████ | 455/500 [01:39<00:10,  4.31it/s]

len(amplitudes) 454
len(amplitudes) 455

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 91%|█████████ | 456/500 [01:40<00:09,  4.86it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 91%|█████████▏| 457/500 [01:40<00:08,  5.36it/s]

len(amplitudes) 456
len(amplitudes) 457

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 92%|█████████▏| 458/500 [01:40<00:08,  5.20it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 92%|█████████▏| 459/500 [01:40<00:07,  5.43it/s]

len(amplitudes) 458
len(amplitudes) 459

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 92%|█████████▏| 460/500 [01:40<00:06,  5.86it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 460

 92%|█████████▏| 461/500 [01:40<00:07,  5.55it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 92%|█████████▏| 462/500 [01:41<00:06,  5.98it/s]

len(amplitudes) 461
len(amplitudes) 462

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 93%|█████████▎| 463/500 [01:41<00:05,  6.31it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 463

 93%|█████████▎| 464/500 [01:41<00:06,  5.71it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 93%|█████████▎| 465/500 [01:41<00:05,  6.02it/s]

len(amplitudes) 464
len(amplitudes) 465

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 93%|█████████▎| 466/500 [01:41<00:05,  6.29it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 93%|█████████▎| 467/500 [01:41<00:05,  6.57it/s]

len(amplitudes) 466
len(amplitudes) 467

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 94%|█████████▎| 468/500 [01:42<00:05,  5.97it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 94%|█████████▍| 469/500 [01:42<00:04,  6.27it/s]

len(amplitudes) 468
len(amplitudes) 469

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 94%|█████████▍| 470/500 [01:42<00:05,  5.70it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 94%|█████████▍| 471/500 [01:42<00:04,  6.01it/s]

len(amplitudes) 470
len(amplitudes) 471

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 94%|█████████▍| 472/500 [01:42<00:04,  6.28it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 95%|█████████▍| 473/500 [01:42<00:04,  6.47it/s]

len(amplitudes) 472
len(amplitudes) 473

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 95%|█████████▍| 474/500 [01:43<00:04,  5.87it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 474

 95%|█████████▌| 475/500 [01:43<00:04,  5.47it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 95%|█████████▌| 476/500 [01:43<00:04,  5.89it/s]

len(amplitudes) 475
len(amplitudes) 476

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 95%|█████████▌| 477/500 [01:43<00:03,  6.25it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 96%|█████████▌| 478/500 [01:43<00:03,  6.54it/s]

len(amplitudes) 477
len(amplitudes) 478

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 96%|█████████▌| 479/500 [01:43<00:03,  6.40it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 479

 96%|█████████▌| 480/500 [01:44<00:03,  5.27it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 480

 96%|█████████▌| 481/500 [01:44<00:03,  5.12it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 481

 96%|█████████▋| 482/500 [01:44<00:03,  4.96it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 482

 97%|█████████▋| 483/500 [01:44<00:03,  4.92it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 483

 97%|█████████▋| 484/500 [01:45<00:03,  4.90it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 97%|█████████▋| 485/500 [01:45<00:02,  5.36it/s]

len(amplitudes) 484
len(amplitudes) 485

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 97%|█████████▋| 486/500 [01:45<00:02,  4.88it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 97%|█████████▋| 487/500 [01:45<00:02,  5.32it/s]

len(amplitudes) 486
len(amplitudes) 487

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 98%|█████████▊| 488/500 [01:45<00:02,  5.81it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 488

 98%|█████████▊| 489/500 [01:45<00:02,  5.45it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 98%|█████████▊| 490/500 [01:46<00:01,  5.81it/s]

len(amplitudes) 489
len(amplitudes) 490

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 98%|█████████▊| 491/500 [01:46<00:01,  6.19it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 98%|█████████▊| 492/500 [01:46<00:01,  6.50it/s]

len(amplitudes) 491
len(amplitudes) 492

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 99%|█████████▊| 493/500 [01:46<00:01,  6.69it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 99%|█████████▉| 494/500 [01:46<00:00,  6.89it/s]

len(amplitudes) 493
len(amplitudes) 494

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 99%|█████████▉| 495/500 [01:46<00:00,  6.98it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 99%|█████████▉| 496/500 [01:46<00:00,  7.02it/s]

len(amplitudes) 495
len(amplitudes) 496

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
 99%|█████████▉| 497/500 [01:47<00:00,  7.02it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
100%|█████████▉| 498/500 [01:47<00:00,  7.05it/s]

len(amplitudes) 497
len(amplitudes) 498

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
100%|█████████▉| 499/500 [01:47<00:00,  6.18it/s]PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

len(amplitudes) 499

100%|██████████| 500/500 [01:47<00:00,  4.65it/s]

In [31]:
test = pd.read_csv(output_csv_path)
test

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation,Amplitude
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,534.658499
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0,73.403575
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,897.182138
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0,2239.571065
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3,60.932284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,2010-01-02T18:19:35.130100Z,UW.LCW,P,-0.491,21,495,46.20482,-122.81132,41.3420,0.604,2010-01-02 18:19:24.788000+00:00,0.473,8,1,9,46.670490,-122.702011,396.0,583.094788
496,496,2010-01-02T18:19:35.140100Z,UW.MTM,P,-0.399,21,496,46.20482,-122.81132,41.3420,0.604,2010-01-02 18:19:24.788000+00:00,0.473,8,1,9,46.025330,-122.212870,1121.0,973.045194
497,497,2010-01-02T18:19:36.490100Z,UW.RVW,S,-0.166,21,497,46.20482,-122.81132,41.3420,0.604,2010-01-02 18:19:24.788000+00:00,0.473,8,1,9,46.149750,-122.742996,504.0,842.538768
498,498,2010-01-02T19:18:22.568400Z,PB.B943,S,-0.775,22,498,47.74010,-123.12926,9.3365,0.680,2010-01-02 19:18:16.657000+00:00,0.514,0,6,6,47.813202,-122.911301,84.2,1281.701150
499,499,2010-01-02T19:18:22.588400Z,PB.B013,S,-0.761,22,499,47.74010,-123.12926,9.3365,0.680,2010-01-02 19:18:16.657000+00:00,0.514,0,6,6,47.813000,-122.910797,75.3,1109.452333